name: Update this repo's README

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.okelet.com/index.xml"
          max_post_count: 10
          comment_tag_name: BLOG-POST-LIST
          template: "* $date: [$title]($url)$newline"
          date_format: "yyyy-mm-dd"
