name: Update this repo's README

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/JasonEtco/rss-to-readme
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://blog.okelet.com/index.xml
          readme-section: blog
          max: 10
          template: "* [{{ title }}]({{ link }})"
